use trap instead of bash -e for better GH log annotation
Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

diff --git a/.github/actions/bench/action.yml b/.github/actions/bench/action.yml
--- a/.github/actions/bench/action.yml
+++ b/.github/actions/bench/action.yml
@@ -61,6 +61,12 @@ runs:
     - name: Run benchmark
       shell: ${{ env.SHELL }}
       run: |
+        catch() {
+          local line_no="$1"
+          echo "::error title=Failed at $line_no: $?"
+        }
+        trap 'catch $LINENO' ERR
+
         tests bench -c ${{ inputs.perf }} --cross-prefix="${{ inputs.cross_prefix }}" \
               --cflags="${{ inputs.cflags }}" --arch-flags="${{ inputs.archflags }}" \
               $([[ ${{ inputs.opt }} == "false" ]] && echo "--no-opt")  \
diff --git a/.github/actions/cbmc/action.yml b/.github/actions/cbmc/action.yml
--- a/.github/actions/cbmc/action.yml
+++ b/.github/actions/cbmc/action.yml
@@ -31,6 +31,12 @@ runs:
       - name: Run CBMC proofs
         shell: ${{ env.SHELL }}
         run: |
+          catch() {
+            local line_no="$1"
+            echo "::error title=cbmc failed at $line_no: $?"
+          }
+          trap 'catch $LINENO' ERR
+
           cd cbmc/proofs;
           echo "::group::cbmc"
           KYBER_K=2 ./run-cbmc-proofs.py --summarize;
