Emulate arm64 binary on x86_64 machine (#60)
* emulate arm64 binary on x86_64 machine

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* Output binaries to bin/ directory

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* add nistkat checksum back

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* use black for python formatting

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* add tests script for running a specify binary

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* factor out the common part of compiling and running a binary

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* add test command for func, nistkat and kat tests

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* compare tests result to the META file

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* add github step summary to tests script if the env var exists

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* update ci to use the tests script

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* cleanup

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* only add -static if is linux x86_64

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* still run kat/nistkat tests even if previous tests failed

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* fix uncompatible makefile macros

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* remove makefile macros

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* place binaries in test/bin instead of bin

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* add --force-qemu flag for tests script

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* add the tests script description to README

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* make ci tests output verbose

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* output full executed make command

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

* fix makefile extra quoting

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

---------

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

diff --git a/scripts/ci/lint b/scripts/ci/lint
--- a/scripts/ci/lint
+++ b/scripts/ci/lint
@@ -46,6 +46,16 @@ echo "::group::Linting shell scripts with shfmt"
 checkerr "Lint shell" "$(shfmt -s -l -i 2 -ci -fn $(shfmt -f $(git grep -l '' :/)))"
 echo "::endgroup::"
 
+echo "::group::Linting python scripts with black"
+if ! diff=$(black --check --diff -q --include scripts/tests "$ROOT"); then
+  echo "::error title=Format error::$diff"
+  SUCCESS=false
+  echo ":x: Lint python" >>"$GITHUB_STEP_SUMMARY"
+else
+  echo ":white_check_mark: Lint Python" >>"$GITHUB_STEP_SUMMARY"
+fi
+echo "::endgroup::"
+
 echo "::group::Linting c files with astyle"
 checkerr "Lint C" "$(astyle $(git ls-files ":/*.c" ":/*.h") --options="$ROOT/.astylerc" --dry-run --formatted | awk '{print $2}')"
 echo "::endgroup::"
