Made setup-nix action more robust
Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

- suppress error annotation in pre-check-nix
- fix if nix shell is different from previous nix shell
- only run magic nix cache once

diff --git a/.github/actions/setup-nix/action.yml b/.github/actions/setup-nix/action.yml
--- a/.github/actions/setup-nix/action.yml
+++ b/.github/actions/setup-nix/action.yml
@@ -16,18 +16,27 @@ runs:
   steps:
     - name: Pre-check nix
       id: pre-check-nix
-      continue-on-error: true
-      shell: bash -leo pipefail {0}
+      if: ${{ env.NIX_SHELL == '' }}
+      shell: bash -lo pipefail {0}
       run: |
+        suppress() {
+          local exit_code="$?"
+          local line_no="$1"
+          echo "Nix check failed at $line_no: $exit_code"
+          echo "install-nix=true" >> $GITHUB_OUTPUT
+          exit 0
+        }
+
+        trap 'suppress $LINENO' ERR
+
         . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
         nix --version
         nix config show | grep -E "^trusted-users = .*$USER"
         nix config show | grep -E "^experimental-features = .*flakes"
         nix config show | grep -E "^experimental-features = .*nix-command"
 
-        echo SHELL="$(which nix) develop --quiet .#${{ inputs.devShell }} -c bash -e {0}" >> $GITHUB_ENV
     - name: Install nix
-      if: steps.pre-check-nix.outcome == 'failure'
+      if: steps.pre-check-nix.outputs.install-nix
       shell: bash -leo pipefail {0}
       run: |
         curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm \
@@ -35,14 +44,19 @@ runs:
         --extra-conf "experimental-features = nix-command flakes"
 
         . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
-        echo SHELL="$(which nix) develop --quiet .#${{ inputs.devShell }} -c bash -e {0}" >> $GITHUB_ENV
     - name: Post-check nix
       continue-on-error: true
       shell: bash -leo pipefail {0}
       run: |
         nix config check
     - uses: DeterminateSystems/magic-nix-cache-action@v8
+      if: ${{ env.NIX_SHELL == '' }}
       continue-on-error: true
+    - name: Set Shell
+      shell: bash -leo pipefail {0}
+      run: |
+        echo NIX_SHELL="${{ inputs.devShell }}" >> $GITHUB_ENV
+        echo SHELL="$(which nix) develop --quiet .#${{ inputs.devShell }} -c bash -e {0}" >> $GITHUB_ENV
     - name: Prepare nix dev shell
       shell: ${{ env.SHELL }}
       run: |
