Add falke and use nix package to have stable astyle version
Signed-off-by: Duc Tri Nguyen <dnguye69@gmu.edu>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,19 +8,41 @@ jobs:
   build_test:
     runs-on: ubuntu-latest
     steps:
-        - uses: actions/checkout@v3
-        - name: install dependencies
-          run: sudo apt-get update && sudo apt install -y astyle jq git
-
-        - name: Astyle version
-          run: astyle --version
-        
-        - name: Astyle test
-          run: |
-            err=$(astyle $(git ls-files "*.c" "*.h") --options=.astylerc --dry-run --formatted)
-            if [[ ${#err} != 0 ]]; then
-                echo "$err" | awk '{split($0,a);print a[2]}' | while IFS= read -r file; do
-                echo "::error file={"$file"},title={checking}::Formatted $file"
-                done
-                exit 1
-            fi
+    - name: install jq
+      shell: bash
+      run: |
+        if ! (command -v jq) &> /dev/null
+        then
+          sudo apt install -y --no-install-recommends jq
+        fi
+    - uses: actions/checkout@v4
+    - id: nixpkgs
+      shell: bash
+      run: |
+        if [ -f flake.lock ]; then
+          nixpkgs="flake:$(cat flake.lock | jq -r '.nodes.nixpkgs.locked // empty | .type + ":" + .owner + "/" + .repo + "/" + .rev')"
+        else
+          nixpkgs=channel:nixos-unstable
+        fi
+        echo "nixpkgs=$nixpkgs" >> "$GITHUB_OUTPUT"
+    - uses: cachix/install-nix-action@v25
+      with:
+        nix_path: nixpkgs=${{ steps.nixpkgs.outputs.nixpkgs }}
+    - name: Prepare nix dev shell
+      shell: nix develop .#ci -c bash -e {0}
+      run: |
+          astyle --version
+    - name: Astyle
+      shell: nix develop .#ci -c bash -e {0}
+      run: |
+          err=$(astyle $(git ls-files "*.c" "*.h") --options=.astylerc --dry-run --formatted)
+          if [[ ${#err} != 0 ]]; then
+            echo "$err" | awk '{split($0,a);print a[2]}' | while IFS= read -r file; do
+              echo "::error file={"$file"},title={checking}::Formatted $file"
+            done
+            exit 1
+          fi
+    - name: Build targets
+      shell: nix develop .#ci -c bash -e {0}
+      run: |
+          make
